import englishMessages from '../../messages/en.json'

import generatedCatalog from '@/generated/component-catalog.json' with { type: 'json' }

/* Editorial catalog context stays hand-curated here. Install-contract order and
 * versions are generated from manifests; commands, routes, and family are
 * deterministic projections. */
export const componentCategories = {
  hero: {
    family: 'pages',
    label: 'Hero',
  },
  features: {
    family: 'pages',
    label: 'Features',
  },
  comparator: {
    family: 'pages',
    label: englishMessages['CatalogBrowser']['categories']['comparator'],
  },
  pricing: {
    family: 'pages',
    label: 'Pricing',
  },
  cta: {
    family: 'pages',
    label: englishMessages['CatalogBrowser']['categories']['cta'],
  },
  contact: {
    family: 'pages',
    label: 'Contact',
  },
  integration: {
    family: 'pages',
    label: englishMessages['CatalogBrowser']['categories']['integration'],
  },
  logos: {
    family: 'pages',
    label: englishMessages['CatalogBrowser']['categories']['logos'],
  },
  testimonials: {
    family: 'pages',
    label: englishMessages['CatalogBrowser']['categories']['testimonials'],
  },
  stats: {
    family: 'pages',
    label: 'Stats',
  },
  faq: {
    family: 'pages',
    label: 'FAQ',
  },
  content: {
    family: 'pages',
    label: 'Content',
  },
  team: {
    family: 'pages',
    label: 'Team',
  },
  embed: {
    family: 'pages',
    label: 'Embed',
  },
  footer: {
    family: 'pages',
    label: 'Footer',
  },
  cards: {
    family: 'posts',
    label: 'Cards',
  },
  archive: {
    family: 'posts',
    label: 'Archive',
  },
  header: {
    family: 'posts',
    label: englishMessages['Components']['post-hero']['target'],
  },
  index: {
    family: 'posts',
    label: 'Index',
  },
  author: {
    family: 'posts',
    label: 'Author',
  },
  newsletter: {
    family: 'posts',
    label: englishMessages['CatalogBrowser']['categories']['newsletter'],
  },
  related: {
    family: 'posts',
    label: 'Related',
  },
} as const

export type ComponentCategory = keyof typeof componentCategories

const componentEditorialEntries = [
  {
    category: 'hero',
    description: englishMessages.Components['hero-basic'].description,
    fields: ['eyebrow', 'title', 'description', 'links', 'proofItems'],
    slug: 'hero-basic',
    target: englishMessages.Components['hero-basic'].target,
    title: englishMessages.Components['hero-basic'].title,
  },
  {
    category: 'hero',
    description: englishMessages.Components['hero-split'].description,
    fields: ['eyebrow', 'title', 'description', 'links', 'image', 'imagePosition', 'highlights'],
    slug: 'hero-split',
    target: englishMessages.Components['hero-split'].target,
    title: englishMessages.Components['hero-split'].title,
  },
  {
    category: 'hero',
    description: englishMessages.Components['hero-video'].description,
    fields: ['eyebrow', 'title', 'description', 'links', 'video', 'poster', 'proofItems'],
    slug: 'hero-video',
    target: englishMessages.Components['hero-video'].target,
    title: englishMessages.Components['hero-video'].title,
  },
  {
    category: 'hero',
    description: englishMessages.Components['hero-product-tilt'].description,
    fields: [
      'eyebrow',
      'title',
      'description',
      'links',
      'productImage',
      'imageCaption',
      'proofItems',
    ],
    slug: 'hero-product-tilt',
    target: englishMessages.Components['hero-product-tilt'].target,
    title: englishMessages.Components['hero-product-tilt'].title,
  },
  {
    category: 'hero',
    description: englishMessages.Components['hero-aurora'].description,
    fields: [
      'eyebrow',
      'title',
      'description',
      'links',
      'metrics',
      'productImage',
      'imageCaption',
      'proofItems',
    ],
    slug: 'hero-aurora',
    target: englishMessages.Components['hero-aurora'].target,
    title: englishMessages.Components['hero-aurora'].title,
  },
  {
    category: 'hero',
    description: englishMessages.Components['hero-kinetic'].description,
    fields: [
      'eyebrow',
      'title',
      'description',
      'links',
      'marqueeItems',
      'image',
      'imageCaption',
      'proofItems',
    ],
    slug: 'hero-kinetic',
    target: englishMessages.Components['hero-kinetic'].target,
    title: englishMessages.Components['hero-kinetic'].title,
  },
  {
    category: 'features',
    description: englishMessages.Components['feature-bento'].description,
    fields: ['eyebrow', 'title', 'description', 'items', 'links'],
    slug: 'feature-bento',
    target: englishMessages.Components['feature-bento'].target,
    title: englishMessages.Components['feature-bento'].title,
  },
  {
    category: 'features',
    description: englishMessages.Components['feature-split'].description,
    fields: ['eyebrow', 'title', 'description', 'items', 'links'],
    slug: 'feature-split',
    target: englishMessages.Components['feature-split'].target,
    title: englishMessages.Components['feature-split'].title,
  },
  {
    category: 'features',
    description: englishMessages.Components['feature-steps'].description,
    fields: ['eyebrow', 'title', 'description', 'items', 'links'],
    slug: 'feature-steps',
    target: englishMessages.Components['feature-steps'].target,
    title: englishMessages.Components['feature-steps'].title,
  },
  {
    category: 'features',
    description: englishMessages.Components['feature-grid-basic'].description,
    fields: ['eyebrow', 'title', 'description', 'items', 'links'],
    slug: 'feature-grid-basic',
    target: englishMessages.Components['feature-grid-basic'].target,
    title: englishMessages.Components['feature-grid-basic'].title,
  },
  {
    category: 'features',
    description: englishMessages.Components['feature-accordion'].description,
    fields: ['eyebrow', 'title', 'description', 'items', 'links'],
    slug: 'feature-accordion',
    target: englishMessages.Components['feature-accordion'].target,
    title: englishMessages.Components['feature-accordion'].title,
  },
  {
    category: 'features',
    description: englishMessages.Components['feature-cards-media'].description,
    fields: ['eyebrow', 'title', 'description', 'items', 'links'],
    slug: 'feature-cards-media',
    target: englishMessages.Components['feature-cards-media'].target,
    title: englishMessages.Components['feature-cards-media'].title,
  },
  {
    category: 'features',
    description: englishMessages.Components['feature-icon-grid'].description,
    fields: ['eyebrow', 'title', 'description', 'items', 'links'],
    slug: 'feature-icon-grid',
    target: englishMessages.Components['feature-icon-grid'].target,
    title: englishMessages.Components['feature-icon-grid'].title,
  },
  {
    category: 'comparator',
    description: englishMessages.Components['comparator-grid'].description,
    fields: ['title', 'description', 'plans', 'features'],
    slug: 'comparator-grid',
    target: englishMessages.Components['comparator-grid'].target,
    title: englishMessages.Components['comparator-grid'].title,
  },
  {
    category: 'comparator',
    description: englishMessages.Components['comparator-table'].description,
    fields: ['title', 'description', 'plans', 'features'],
    slug: 'comparator-table',
    target: englishMessages.Components['comparator-table'].target,
    title: englishMessages.Components['comparator-table'].title,
  },
  {
    category: 'comparator',
    description: englishMessages.Components['comparator-stack'].description,
    fields: ['title', 'description', 'plans'],
    slug: 'comparator-stack',
    target: englishMessages.Components['comparator-stack'].target,
    title: englishMessages.Components['comparator-stack'].title,
  },
  {
    category: 'pricing',
    description: englishMessages.Components['pricing-cards'].description,
    fields: ['eyebrow', 'title', 'description', 'plans'],
    slug: 'pricing-cards',
    target: englishMessages.Components['pricing-cards'].target,
    title: englishMessages.Components['pricing-cards'].title,
  },
  {
    category: 'pricing',
    description: englishMessages.Components['pricing-cards-muted'].description,
    fields: ['eyebrow', 'title', 'description', 'plans'],
    slug: 'pricing-cards-muted',
    target: englishMessages.Components['pricing-cards-muted'].target,
    title: englishMessages.Components['pricing-cards-muted'].title,
  },
  {
    category: 'pricing',
    description: englishMessages.Components['pricing-cards-cta'].description,
    fields: ['eyebrow', 'title', 'description', 'plans'],
    slug: 'pricing-cards-cta',
    target: englishMessages.Components['pricing-cards-cta'].target,
    title: englishMessages.Components['pricing-cards-cta'].title,
  },
  {
    category: 'pricing',
    description: englishMessages.Components['pricing-split'].description,
    fields: ['eyebrow', 'title', 'description', 'plans'],
    slug: 'pricing-split',
    target: englishMessages.Components['pricing-split'].target,
    title: englishMessages.Components['pricing-split'].title,
  },
  {
    category: 'pricing',
    description: englishMessages.Components['pricing-enterprise'].description,
    fields: ['eyebrow', 'title', 'description', 'plans', 'logos'],
    slug: 'pricing-enterprise',
    target: englishMessages.Components['pricing-enterprise'].target,
    title: englishMessages.Components['pricing-enterprise'].title,
  },
  {
    category: 'cta',
    description: englishMessages.Components['call-to-action-centered'].description,
    fields: ['title', 'description', 'links'],
    slug: 'call-to-action-centered',
    target: englishMessages.Components['call-to-action-centered'].target,
    title: englishMessages.Components['call-to-action-centered'].title,
  },
  {
    category: 'cta',
    description: englishMessages.Components['call-to-action-boxed'].description,
    fields: ['title', 'description', 'links'],
    slug: 'call-to-action-boxed',
    target: englishMessages.Components['call-to-action-boxed'].target,
    title: englishMessages.Components['call-to-action-boxed'].title,
  },
  {
    category: 'cta',
    description: englishMessages.Components['call-to-action-split'].description,
    fields: ['title', 'description', 'assurance', 'links'],
    slug: 'call-to-action-split',
    target: englishMessages.Components['call-to-action-split'].target,
    title: englishMessages.Components['call-to-action-split'].title,
  },
  {
    category: 'cta',
    description: englishMessages.Components['call-to-action-signup'].description,
    fields: ['title', 'description', 'emailPlaceholder', 'submitLabel', 'action'],
    slug: 'call-to-action-signup',
    target: englishMessages.Components['call-to-action-signup'].target,
    title: englishMessages.Components['call-to-action-signup'].title,
  },
  {
    category: 'contact',
    description: englishMessages.Components['contact-routing-form'].description,
    fields: [
      'eyebrow',
      'title',
      'description',
      'channels',
      'formTitle',
      'formDescription',
      'formLabels',
      'submitLabel',
      'action',
    ],
    slug: 'contact-routing-form',
    target: englishMessages.Components['contact-routing-form'].target,
    title: englishMessages.Components['contact-routing-form'].title,
  },
  {
    category: 'contact',
    description: englishMessages.Components['contact-channels'].description,
    fields: ['eyebrow', 'title', 'description', 'channels', 'footnote'],
    slug: 'contact-channels',
    target: englishMessages.Components['contact-channels'].target,
    title: englishMessages.Components['contact-channels'].title,
  },
  {
    category: 'integration',
    description: englishMessages.Components['integration-orbit'].description,
    fields: ['heading', 'subtext', 'integrations', 'featuredLogo'],
    slug: 'integration-orbit',
    target: englishMessages.Components['integration-orbit'].target,
    title: englishMessages.Components['integration-orbit'].title,
  },
  {
    category: 'integration',
    description: englishMessages.Components['integration-marquee'].description,
    fields: ['heading', 'subtext', 'integrations', 'featuredLogo'],
    slug: 'integration-marquee',
    target: englishMessages.Components['integration-marquee'].target,
    title: englishMessages.Components['integration-marquee'].title,
  },
  {
    category: 'integration',
    description: englishMessages.Components['integration-connect'].description,
    fields: ['heading', 'subtext', 'integrations', 'featuredLogo'],
    slug: 'integration-connect',
    target: englishMessages.Components['integration-connect'].target,
    title: englishMessages.Components['integration-connect'].title,
  },
  {
    category: 'integration',
    description: englishMessages.Components['integration-cluster'].description,
    fields: ['heading', 'subtext', 'integrations', 'featuredLogo', 'links'],
    slug: 'integration-cluster',
    target: englishMessages.Components['integration-cluster'].target,
    title: englishMessages.Components['integration-cluster'].title,
  },
  {
    category: 'integration',
    description: englishMessages.Components['integration-split'].description,
    fields: ['heading', 'subtext', 'integrations', 'featuredLogo', 'links'],
    slug: 'integration-split',
    target: englishMessages.Components['integration-split'].target,
    title: englishMessages.Components['integration-split'].title,
  },
  {
    category: 'integration',
    description: englishMessages.Components['integration-grid'].description,
    fields: ['heading', 'subtext', 'integrations'],
    slug: 'integration-grid',
    target: englishMessages.Components['integration-grid'].target,
    title: englishMessages.Components['integration-grid'].title,
  },
  {
    category: 'integration',
    description: englishMessages.Components['integration-list'].description,
    fields: ['heading', 'subtext', 'integrations'],
    slug: 'integration-list',
    target: englishMessages.Components['integration-list'].target,
    title: englishMessages.Components['integration-list'].title,
  },
  {
    category: 'integration',
    description: englishMessages.Components['integration-testimonial'].description,
    fields: ['heading', 'subtext', 'integrations', 'quote', 'author', 'role'],
    slug: 'integration-testimonial',
    target: englishMessages.Components['integration-testimonial'].target,
    title: englishMessages.Components['integration-testimonial'].title,
  },
  {
    category: 'logos',
    description: englishMessages.Components['logo-cloud-marquee'].description,
    fields: ['heading', 'logos'],
    slug: 'logo-cloud-marquee',
    target: englishMessages.Components['logo-cloud-marquee'].target,
    title: englishMessages.Components['logo-cloud-marquee'].title,
  },
  {
    category: 'logos',
    description: englishMessages.Components['logo-cloud-hover'].description,
    fields: ['heading', 'logos', 'links'],
    slug: 'logo-cloud-hover',
    target: englishMessages.Components['logo-cloud-hover'].target,
    title: englishMessages.Components['logo-cloud-hover'].title,
  },
  {
    category: 'logos',
    description: englishMessages.Components['logo-cloud-grid'].description,
    fields: ['heading', 'logos'],
    slug: 'logo-cloud-grid',
    target: englishMessages.Components['logo-cloud-grid'].target,
    title: englishMessages.Components['logo-cloud-grid'].title,
  },
  {
    category: 'logos',
    description: englishMessages.Components['logo-cloud-inline'].description,
    fields: ['heading', 'logos'],
    slug: 'logo-cloud-inline',
    target: englishMessages.Components['logo-cloud-inline'].target,
    title: englishMessages.Components['logo-cloud-inline'].title,
  },
  {
    category: 'logos',
    description: englishMessages.Components['logo-cloud-inline-wrap'].description,
    fields: ['heading', 'logos'],
    slug: 'logo-cloud-inline-wrap',
    target: englishMessages.Components['logo-cloud-inline-wrap'].target,
    title: englishMessages.Components['logo-cloud-inline-wrap'].title,
  },
  {
    category: 'testimonials',
    description: englishMessages.Components['testimonials-grid'].description,
    fields: ['eyebrow', 'title', 'description', 'testimonials'],
    slug: 'testimonials-grid',
    target: englishMessages.Components['testimonials-grid'].target,
    title: englishMessages.Components['testimonials-grid'].title,
  },
  {
    category: 'testimonials',
    description: englishMessages.Components['testimonials-bento'].description,
    fields: ['eyebrow', 'title', 'description', 'testimonials'],
    slug: 'testimonials-bento',
    target: englishMessages.Components['testimonials-bento'].target,
    title: englishMessages.Components['testimonials-bento'].title,
  },
  {
    category: 'testimonials',
    description: englishMessages.Components['testimonials-wall'].description,
    fields: ['eyebrow', 'title', 'description', 'testimonials'],
    slug: 'testimonials-wall',
    target: englishMessages.Components['testimonials-wall'].target,
    title: englishMessages.Components['testimonials-wall'].title,
  },
  {
    category: 'testimonials',
    description: englishMessages.Components['testimonials-rating'].description,
    fields: ['eyebrow', 'title', 'description', 'testimonials'],
    slug: 'testimonials-rating',
    target: englishMessages.Components['testimonials-rating'].target,
    title: englishMessages.Components['testimonials-rating'].title,
  },
  {
    category: 'testimonials',
    description: englishMessages.Components['testimonials-spotlight'].description,
    fields: ['quote', 'author', 'role', 'avatar'],
    slug: 'testimonials-spotlight',
    target: englishMessages.Components['testimonials-spotlight'].target,
    title: englishMessages.Components['testimonials-spotlight'].title,
  },
  {
    category: 'testimonials',
    description: englishMessages.Components['testimonials-quote'].description,
    fields: ['quote', 'author', 'role', 'avatar'],
    slug: 'testimonials-quote',
    target: englishMessages.Components['testimonials-quote'].target,
    title: englishMessages.Components['testimonials-quote'].title,
  },
  {
    category: 'stats',
    description: englishMessages.Components['stats-proof'].description,
    fields: [
      'eyebrow',
      'title',
      'description',
      'body',
      'metrics',
      'quote',
      'author',
      'role',
      'logo',
      'logoLabel',
    ],
    slug: 'stats-proof',
    target: englishMessages.Components['stats-proof'].target,
    title: englishMessages.Components['stats-proof'].title,
  },
  {
    category: 'stats',
    description: englishMessages.Components['stats-grid'].description,
    fields: ['eyebrow', 'title', 'description', 'metrics'],
    slug: 'stats-grid',
    target: englishMessages.Components['stats-grid'].target,
    title: englishMessages.Components['stats-grid'].title,
  },
  {
    category: 'stats',
    description: englishMessages.Components['stats-card'].description,
    fields: ['eyebrow', 'title', 'metrics'],
    slug: 'stats-card',
    target: englishMessages.Components['stats-card'].target,
    title: englishMessages.Components['stats-card'].title,
  },
  {
    category: 'stats',
    description: englishMessages.Components['stats-inline'].description,
    fields: ['eyebrow', 'title', 'description', 'metrics'],
    slug: 'stats-inline',
    target: englishMessages.Components['stats-inline'].target,
    title: englishMessages.Components['stats-inline'].title,
  },
  {
    category: 'faq',
    description: englishMessages.Components['faq-split'].description,
    fields: ['eyebrow', 'title', 'description', 'items', 'links'],
    slug: 'faq-split',
    target: englishMessages.Components['faq-split'].target,
    title: englishMessages.Components['faq-split'].title,
  },
  {
    category: 'faq',
    description: englishMessages.Components['faq-accordion'].description,
    fields: ['eyebrow', 'title', 'description', 'items', 'links'],
    slug: 'faq-accordion',
    target: englishMessages.Components['faq-accordion'].target,
    title: englishMessages.Components['faq-accordion'].title,
  },
  {
    category: 'faq',
    description: englishMessages.Components['faq-grouped'].description,
    fields: ['eyebrow', 'title', 'description', 'groups'],
    slug: 'faq-grouped',
    target: englishMessages.Components['faq-grouped'].target,
    title: englishMessages.Components['faq-grouped'].title,
  },
  {
    category: 'faq',
    description: englishMessages.Components['faq-card'].description,
    fields: ['eyebrow', 'title', 'description', 'items', 'links'],
    slug: 'faq-card',
    target: englishMessages.Components['faq-card'].target,
    title: englishMessages.Components['faq-card'].title,
  },
  {
    category: 'faq',
    description: englishMessages.Components['faq-icons'].description,
    fields: ['eyebrow', 'title', 'description', 'items'],
    slug: 'faq-icons',
    target: englishMessages.Components['faq-icons'].target,
    title: englishMessages.Components['faq-icons'].title,
  },
  {
    category: 'faq',
    description: englishMessages.Components['faq-grid'].description,
    fields: ['eyebrow', 'title', 'description', 'items'],
    slug: 'faq-grid',
    target: englishMessages.Components['faq-grid'].target,
    title: englishMessages.Components['faq-grid'].title,
  },
  {
    category: 'content',
    description: englishMessages.Components['content-showcase'].description,
    fields: ['eyebrow', 'title', 'paragraphs', 'image', 'features'],
    slug: 'content-showcase',
    target: englishMessages.Components['content-showcase'].target,
    title: englishMessages.Components['content-showcase'].title,
  },
  {
    category: 'content',
    description: englishMessages.Components['content-image-lead'].description,
    fields: ['eyebrow', 'title', 'paragraphs', 'image', 'links'],
    slug: 'content-image-lead',
    target: englishMessages.Components['content-image-lead'].target,
    title: englishMessages.Components['content-image-lead'].title,
  },
  {
    category: 'content',
    description: englishMessages.Components['content-feature-split'].description,
    fields: ['eyebrow', 'title', 'paragraphs', 'features', 'image'],
    slug: 'content-feature-split',
    target: englishMessages.Components['content-feature-split'].target,
    title: englishMessages.Components['content-feature-split'].title,
  },
  {
    category: 'content',
    description: englishMessages.Components['content-feature-media'].description,
    fields: ['eyebrow', 'title', 'paragraphs', 'features', 'image'],
    slug: 'content-feature-media',
    target: englishMessages.Components['content-feature-media'].target,
    title: englishMessages.Components['content-feature-media'].title,
  },
  {
    category: 'content',
    description: englishMessages.Components['content-image-frame'].description,
    fields: ['eyebrow', 'title', 'paragraphs', 'image', 'backgroundImage'],
    slug: 'content-image-frame',
    target: englishMessages.Components['content-image-frame'].target,
    title: englishMessages.Components['content-image-frame'].title,
  },
  {
    category: 'content',
    description: englishMessages.Components['content-split-rows'].description,
    fields: ['eyebrow', 'title', 'paragraphs', 'rows'],
    slug: 'content-split-rows',
    target: englishMessages.Components['content-split-rows'].target,
    title: englishMessages.Components['content-split-rows'].title,
  },
  {
    category: 'content',
    description: englishMessages.Components['content-rows'].description,
    fields: ['eyebrow', 'title', 'paragraphs', 'rows'],
    slug: 'content-rows',
    target: englishMessages.Components['content-rows'].target,
    title: englishMessages.Components['content-rows'].title,
  },
  {
    category: 'content',
    description: englishMessages.Components['content-stats'].description,
    fields: ['eyebrow', 'title', 'paragraphs', 'features', 'stats'],
    slug: 'content-stats',
    target: englishMessages.Components['content-stats'].target,
    title: englishMessages.Components['content-stats'].title,
  },
  {
    category: 'content',
    description: englishMessages.Components['content-quote'].description,
    fields: ['eyebrow', 'title', 'paragraphs', 'image', 'quote', 'citation', 'logo', 'logoLabel'],
    slug: 'content-quote',
    target: englishMessages.Components['content-quote'].target,
    title: englishMessages.Components['content-quote'].title,
  },
  {
    category: 'content',
    description: englishMessages.Components['content-community'].description,
    fields: ['eyebrow', 'title', 'paragraphs', 'avatars'],
    slug: 'content-community',
    target: englishMessages.Components['content-community'].target,
    title: englishMessages.Components['content-community'].title,
  },
  {
    category: 'content',
    description: englishMessages.Components['content-columns'].description,
    fields: ['eyebrow', 'title', 'paragraphs', 'links'],
    slug: 'content-columns',
    target: englishMessages.Components['content-columns'].target,
    title: englishMessages.Components['content-columns'].title,
  },
  {
    category: 'content',
    description: englishMessages.Components['content-list'].description,
    fields: ['eyebrow', 'title', 'items'],
    slug: 'content-list',
    target: englishMessages.Components['content-list'].target,
    title: englishMessages.Components['content-list'].title,
  },
  {
    category: 'content',
    description: englishMessages.Components['content-list-columns'].description,
    fields: ['eyebrow', 'title', 'items'],
    slug: 'content-list-columns',
    target: englishMessages.Components['content-list-columns'].target,
    title: englishMessages.Components['content-list-columns'].title,
  },
  {
    category: 'content',
    description: englishMessages.Components['content-list-icons'].description,
    fields: ['eyebrow', 'title', 'description', 'items'],
    slug: 'content-list-icons',
    target: englishMessages.Components['content-list-icons'].target,
    title: englishMessages.Components['content-list-icons'].title,
  },
  {
    category: 'team',
    description: englishMessages.Components['team-grid'].description,
    fields: ['eyebrow', 'title', 'description', 'members'],
    slug: 'team-grid',
    target: englishMessages.Components['team-grid'].target,
    title: englishMessages.Components['team-grid'].title,
  },
  {
    category: 'team',
    description: englishMessages.Components['team-bios'].description,
    fields: ['eyebrow', 'title', 'description', 'members'],
    slug: 'team-bios',
    target: englishMessages.Components['team-bios'].target,
    title: englishMessages.Components['team-bios'].title,
  },
  {
    category: 'team',
    description: englishMessages.Components['team-roster'].description,
    fields: ['eyebrow', 'title', 'groups'],
    slug: 'team-roster',
    target: englishMessages.Components['team-roster'].target,
    title: englishMessages.Components['team-roster'].title,
  },
  {
    category: 'embed',
    description: englishMessages.Components['embed-basic'].description,
    fields: ['url', 'title', 'aspectRatio', 'caption', 'allowFullscreen'],
    slug: 'embed-basic',
    target: englishMessages.Components['embed-basic'].target,
    title: englishMessages.Components['embed-basic'].title,
  },
  {
    category: 'footer',
    description: englishMessages.Components['footer-columns'].description,
    fields: ['logo', 'brandLabel', 'copyright', 'tagline', 'groups'],
    slug: 'footer-columns',
    target: englishMessages.Components['footer-columns'].target,
    title: englishMessages.Components['footer-columns'].title,
  },
  {
    category: 'footer',
    description: englishMessages.Components['footer-simple'].description,
    fields: ['logo', 'brandLabel', 'copyright', 'links'],
    slug: 'footer-simple',
    target: englishMessages.Components['footer-simple'].target,
    title: englishMessages.Components['footer-simple'].title,
  },
  {
    category: 'footer',
    description: englishMessages.Components['footer-centered'].description,
    fields: ['logo', 'brandLabel', 'copyright', 'tagline', 'links', 'legalLinks'],
    slug: 'footer-centered',
    target: englishMessages.Components['footer-centered'].target,
    title: englishMessages.Components['footer-centered'].title,
  },
] as const

const editorialBySlug = new Map<string, (typeof componentEditorialEntries)[number]>(
  componentEditorialEntries.map((component) => [component.slug, component]),
)

export const componentEntries = generatedCatalog.components.map((generated) => {
  const entry = editorialBySlug.get(generated.slug)

  if (!entry) {
    throw new Error(`Generated component "${generated.slug}" has no editorial catalog entry.`)
  }

  return {
    ...entry,
    command: `npx payload-components add ${entry.slug}`,
    family: componentCategories[entry.category].family,
    href: `/docs/components/${entry.slug}`,
    version: generated.version,
  }
})

if (componentEntries.length !== componentEditorialEntries.length) {
  throw new Error('Editorial component catalog contains an entry that is not in the registry.')
}

export type ComponentEntry = (typeof componentEntries)[number]

/* The planned posts suite is a set of public proposals that will ship through
 * the same source, manifest, docs, and installer workflow as the MIT registry. */
export const upcomingComponents = [
  {
    category: 'cards',
    description: englishMessages.Components['post-card'].description,
    family: 'posts',
    slug: 'post-card',
    target: englishMessages.Components['post-card'].target,
    title: englishMessages.Components['post-card'].title,
  },
  {
    category: 'archive',
    description: englishMessages.Components['post-archive'].description,
    family: 'posts',
    slug: 'post-archive',
    target: englishMessages.Components['post-archive'].target,
    title: englishMessages.Components['post-archive'].title,
  },
  {
    category: 'header',
    description: englishMessages.Components['post-hero'].description,
    family: 'posts',
    slug: 'post-hero',
    target: englishMessages.Components['post-hero'].target,
    title: englishMessages.Components['post-hero'].title,
  },
  {
    category: 'index',
    description: englishMessages.Components['featured-post'].description,
    family: 'posts',
    slug: 'featured-post',
    target: englishMessages.Components['featured-post'].target,
    title: englishMessages.Components['featured-post'].title,
  },
  {
    category: 'index',
    description: englishMessages.Components['post-list'].description,
    family: 'posts',
    slug: 'post-list',
    target: englishMessages.Components['post-list'].target,
    title: englishMessages.Components['post-list'].title,
  },
  {
    category: 'author',
    description: englishMessages.Components['author-card'].description,
    family: 'posts',
    slug: 'author-card',
    target: englishMessages.Components['author-card'].target,
    title: englishMessages.Components['author-card'].title,
  },
  {
    category: 'newsletter',
    description: englishMessages.Components['newsletter-callout'].description,
    family: 'posts',
    slug: 'newsletter-callout',
    target: englishMessages.Components['newsletter-callout'].target,
    title: englishMessages.Components['newsletter-callout'].title,
  },
  {
    category: 'related',
    description: englishMessages.Components['related-posts'].description,
    family: 'posts',
    slug: 'related-posts',
    target: englishMessages.Components['related-posts'].target,
    title: englishMessages.Components['related-posts'].title,
  },
] as const

export type UpcomingComponent = (typeof upcomingComponents)[number]

export const componentsIntro = englishMessages['Landing']['catalog']['intro']

export const componentFamilies = {
  pages: {
    countLabel: englishMessages['Landing']['catalog']['familyCount'],
    description: englishMessages['Landing']['catalog']['familyDescription'],
    name: englishMessages['Landing']['catalog']['familyName'],
  },
  posts: {
    countLabel: englishMessages['CatalogBrowser']['inDevelopment'],
    description:
      'Editorial surfaces for the Posts collection — component-level installs, no block wiring needed. In development.',
    name: englishMessages['CatalogBrowser']['families']['posts'],
  },
} as const
