version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      next-react:
        patterns:
          - eslint-config-next
          - next
          - react
          - react-dom
      test-tooling:
        patterns:
          - '@playwright/*'
          - vite
          - vite-tsconfig-paths
          - vitest
      documentation-tooling:
        patterns:
          - 'fumadocs-*'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
