import { defineRouting } from 'next-intl/routing'

import { defaultSiteLocale, siteLocales } from '@/i18n/config'

/**
 * Public locale URLs are explicit, except English which keeps the project's
 * original unprefixed URLs. Detection is intentionally disabled: analytics by
 * country is not a reliable language signal and visitors remain in control.
 * SEO alternate links are resource-aware and therefore generated by the app.
 */
export const routing = defineRouting({
  alternateLinks: false,
  defaultLocale: defaultSiteLocale,
  localeDetection: false,
  localePrefix: 'as-needed',
  locales: siteLocales,
})
